# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = { "vm.swappiness" = 40; };
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=50%" "mode=755" ];
  };

  fileSystems."/nix" = {
    neededForBoot = true;
    device = "/dev/disk/by-uuid/02bdb867-4ea2-4ea0-8f38-aaf5cc265870";
    fsType = "btrfs";
    options = [ "subvol=@nix" "noatime" "compress-force=zstd" ];
  };

  fileSystems."/nix/persist" = {
    neededForBoot = true;
    device = "/dev/disk/by-uuid/02bdb867-4ea2-4ea0-8f38-aaf5cc265870";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress-force=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0A0B-F81B";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/mnt/disk2" = {
    device = "/dev/disk/by-uuid/f597bcf2-0d98-456f-9890-4b39f1069c2d";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress-force=zstd" "autodefrag" ];
  };

  swapDevices = [{
    device = "/var/swapfile";
    size = 16 * 1024;
  }];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  environment.persistence."/nix/persist" = {
    hideMounts = true;
    directories = [
      "/var/log"
      "/var/lib/systemd/coredump"
      "/var/lib/nixos"
      "/var/tmp"
      "/etc/nixos"
      "/etc/NetworkManager/system-connections"
      "/opt/containers"
    ];
    files = [
      # machine-id is used by systemd for the journal, if you don't persist this
      # file you won't be able to easily use journalctl to look at journals for
      # previous boots.
      "/etc/machine-id"
      "/etc/adjtime"
    ];
  };
}
